
pool:
  vmImage: 'ubuntu-16.04'

variables:
  IMAGE: 'docker.io/pywr/pywr-ci-example'

stages:
- stage: Test
  jobs:
  - job: Linting
    container: 'python:3.7-slim-stretch'
    steps:
    - script: |
        export PATH=$PATH:~/.local/bin
        pip3 install pipenv
        python3 -m venv venv
        source venv/bin/activate
        pipenv install --dev --deploy
        flake8 --version
        flake8 app

  - job: Mypy
    container: 'python:3.7-slim-stretch'
    steps:
    - script: |
        export PATH=$PATH:~/.local/bin
        pip3 install pipenv
        python3 -m venv venv
        source venv/bin/activate
        pipenv install --dev --deploy
        mypy --version
        mypy app


- stage: BuildImage
  jobs:
    - job: Build
      container: 'tomkukral/buildah'
      steps:
        - script: |
            podman version
            buildah version
            podman build -t $IMAGE .
