
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Dependencies
  jobs:
  - job: Dependices
    container: 'python:3.7-slim-stretch'
    steps:
    - script: |
        pip3 install pipenv
        python3 -m venv venv
        source venv/bin/activate
        pipenv install --dev --deploy
    - publish: venv/
      artifact: VirtualEnv

- stage: Test
  jobs:
  - job: Linting
    container: 'python:3.7-slim-stretch'
    steps:
    - download: current
      artifact: VirtualEnv
    - script: |
        source venv/bin/activate
        flake8 --version
        flake8 app

  - job: Mypy
    container: 'python:3.7-slim-stretch'
    steps:
    - download: current
      artifact: VirtualEnv
    - script: |
        source venv/bin/activate
        mypy --version
        mypy app

