
pool:
  vmImage: 'ubuntu-16.04'

variables:
  image: 'docker.io/pywr/pywr-ci-example'

stages:
- stage: Test
  jobs:
  - job: Linting
    container: 'python:3.8-slim'
    steps:
    - script: |
        export PATH=$PATH:~/.local/bin
        pip3 install pipenv
        python3 -m venv venv
        source venv/bin/activate
        pipenv install --dev --deploy
        flake8 --version
        flake8 app

  - job: Mypy
    container: 'python:3.8-slim'
    steps:
    - script: |
        export PATH=$PATH:~/.local/bin
        pip3 install pipenv
        python3 -m venv venv
        source venv/bin/activate
        pipenv install --dev --deploy
        mypy --version
        mypy app

  - job: Run
    container: 'python:3.8-slim'
    steps:
    - script: |
        export PATH=$PATH:~/.local/bin
        pip3 install pipenv
        python3 -m venv venv
        source venv/bin/activate
        pipenv install --dev --deploy
        python app/thames.py historic-run
      env:
        AZURE_BLOB_CONNECT_STR: $(AZURE_BLOB_CONNECT_STR) # Map secret variable

- stage: BuildImage
  jobs:
  - job: Build
    displayName: Build job
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(image)
        containerRegistry: 'dockerHub'
